[tool.black] # from https://github.com/ambv/black#configuration-format
line-length = 80
py36 = true
py37 = true
include = '\.pyi?$'
exclude = '''
  /(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | node_modules
    | docs
  )/
'''
